### ISSUE TITLE
Unable to add pytest argument "--reruns=1"

### ISSUE THREAD

**Issue by siddgpt** [pavelzw/pytest-action#17]
I am trying to add additional argument for test path and reruns, but it fails when I add the argument for rerun

**Comment by pavelzw** [comment]
Can you provide me a failing example workflow?

**Comment by pavelzw** [comment]
Should probably be fixed with https://github.com/pavelzw/pytest-action/commit/510c5e90c360a185039bea56ce8b3e7e51a16507
If this is still an issue, feel free to reopen.
