### ISSUE TITLE
[Question] update same PR comment

### ISSUE THREAD

**Issue by codebydant** [pavelzw/pytest-action#3]
Hi @pavelzw,

Thanks for this wonderful tool. Is there a parameter to make the PR comment update instead of creating a new one each the workflow run is executed?

**Comment by pavelzw** [comment]
Hi,

This action actually doesn't post any PR comments but it exports them to the [GitHub Job Summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/).

But I like your suggestion and will probably implement this someday, as soon as I find time to do it.
