### ISSUE TITLE
Add poetry support

### ISSUE THREAD

**Issue by LordFckHelmchen** [pavelzw/pytest-action#5]
Hey @pavelzw!

I really like your action, but am heavily using poetry in my projects. It would be great if the action could have an option to run pytest via poetry.  You could add it as in input argument (e.g. inputs.usePoetry) and then call `poetry run pytest "${args[@]}"` instead of the standard call.

**Comment by pavelzw** [comment]
Thanks for the suggestion!

What do you think of adding an argument `custom-pytest` where you can add `poetry run pytest`? Like this, we could also cover the case of other custom `pytest` executables or something like `micromamba run -n customenv pytest`.

**Comment by LordFckHelmchen** [comment]
Hey @pavelzw - perfectly valid solution! Thanks a lot for the quick action. Will start to use it on my project!
